In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df=pd.read_csv('/content/drive/MyDrive/IITBHU/netflix_titles - Copy.csv')

In [4]:
df.head(3)

show_id     type  title           director  \
0        1  TV Show     3%                NaN   
1        2    Movie   7:19  Jorge Michel Grau   
2        3    Movie  23:59       Gilbert Chan   

                                                cast    country date_added  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...     Brazil  14-Aug-20   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...     Mexico  23-Dec-16   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...  Singapore  20-Dec-18   

   release_year rating   duration  \
0          2020  TV-MA  4 Seasons   
1          2016  TV-MA     93 min   
2          2011      R     78 min   

                                           listed_in  \
0  International TV Shows, TV Dramas, TV Sci-Fi &...   
1                       Dramas, International Movies   
2                Horror Movies, International Movies   

                                         description  
0  In a future where the elite inhabit an island ...  
1  After a devastating earthquake hits Mexico Cit...  
2  When an army recruit is found dead, his fellow...

In [5]:
df.shape

(7787, 12)

In [6]:
columns = ['cast','director','description','title']

In [7]:
df[columns].head(3)

cast           director  \
0  João Miguel, Bianca Comparato, Michel Gomes, R...                NaN   
1  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...  Jorge Michel Grau   
2  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...       Gilbert Chan   

                                         description  title  
0  In a future where the elite inhabit an island ...     3%  
1  After a devastating earthquake hits Mexico Cit...   7:19  
2  When an army recruit is found dead, his fellow...  23:59

In [8]:
df[columns].isnull().values.any()

True

In [9]:
df.dropna()

show_id     type       title           director  \
1           2    Movie        7:19  Jorge Michel Grau   
2           3    Movie       23:59       Gilbert Chan   
3           4    Movie           9        Shane Acker   
4           5    Movie          21     Robert Luketic   
5           6  TV Show          46        Serdar Akar   
...       ...      ...         ...                ...   
7778     7779    Movie  Zombieland    Ruben Fleischer   
7780     7781    Movie         Zoo       Shlok Sharma   
7781     7782    Movie        Zoom       Peter Hewitt   
7782     7783    Movie        Zozo        Josef Fares   
7783     7784    Movie      Zubaan        Mozez Singh   

                                                   cast  \
1     Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2     Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3     Elijah Wood, John C. Reilly, Jennifer Connelly...   
4     Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
5     Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...   
...                                                 ...   
7778  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...   
7780  Shashank Arora, Shweta Tripathi, Rahul Kumar, ...   
7781  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...   
7782  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   

                                                country date_added  \
1                                                Mexico  23-Dec-16   
2                                             Singapore  20-Dec-18   
3                                         United States  16-Nov-17   
4                                         United States   1-Jan-20   
5                                                Turkey   1-Jul-17   
...                                                 ...        ...   
7778                                      United States   1-Nov-19   
7780                                              India   1-Jul-18   
7781                                      United States  11-Jan-20   
7782  Sweden, Czech Republic, United Kingdom, Denmar...  19-Oct-20   
7783                                              India   2-Mar-19   

      release_year rating  duration  \
1             2016  TV-MA    93 min   
2             2011      R    78 min   
3             2009  PG-13    80 min   
4             2008  PG-13   123 min   
5             2016  TV-MA  1 Season   
...            ...    ...       ...   
7778          2009      R    88 min   
7780          2018  TV-MA    94 min   
7781          2006     PG    88 min   
7782          2005  TV-MA    99 min   
7783          2015  TV-14   111 min   

                                              listed_in  \
1                          Dramas, International Movies   
2                   Horror Movies, International Movies   
3     Action & Adventure, Independent Movies, Sci-Fi...   
4                                                Dramas   
5       International TV Shows, TV Dramas, TV Mysteries   
...                                                 ...   
7778                            Comedies, Horror Movies   
7780   Dramas, Independent Movies, International Movies   
7781                 Children & Family Movies, Comedies   
7782                       Dramas, International Movies   
7783     Dramas, International Movies, Music & Musicals   

                                            description  
1     After a devastating earthquake hits Mexico Cit...  
2     When an army recruit is found dead, his fellow...  
3     In a postapocalyptic world, rag-doll robots hi...  
4     A brilliant group of students become card-coun...  
5     A genetics professor experiments with a treatm...  
...                                                 ...  
7778  Looking to survive in a world taken over by zo...  
7780  A drug dealer starts having doubts about his t...  
7781  Dragged from civilian life, a former superhero...  
7782  When Le

In [10]:
def get_important_features(data):
  important_features = []
  for i in range(0, data.shape[0]):
    important_features.append(data['cast'][i]+' '+data['director'][i]+' '+data['description'][i]+' '+data['title'][i])

  return important_features

In [11]:
df['important_features'] = df['cast'].astype(str) + ' ' + df['director'].astype(str) + ' '+ df['description'].astype(str) + ' '+df['title']
df

show_id     type                                    title  \
0           1  TV Show                                       3%   
1           2    Movie                                     7:19   
2           3    Movie                                    23:59   
3           4    Movie                                        9   
4           5    Movie                                       21   
...       ...      ...                                      ...   
7782     7783    Movie                                     Zozo   
7783     7784    Movie                                   Zubaan   
7784     7785    Movie                        Zulu Man in Japan   
7785     7786  TV Show                    Zumbo's Just Desserts   
7786     7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

                                                country date_added  \
0                                                Brazil  14-Aug-20   
1                                                Mexico  23-Dec-16   
2                                             Singapore  20-Dec-18   
3                                         United States  16-Nov-17   
4                                         United States   1-Jan-20   
...                                                 ...        ...   
7782  Sweden, Czech Republic, United Kingdom, Denmar...  19-Oct-20   
7783                                              India   2-Mar-19   
7784                                                NaN  25-Sep-20   
7785                                          Australia  31-Oct-20   
7786              United Kingdom, Canada, United States   1-Mar-20   

      release_year rating   duration  \
0             2020  TV-MA  4 Seasons   
1             2016  TV-MA     93 min   
2             2011      R     78 min   
3             2009  PG-13     80 min   
4             2008  PG-13    123 min   
...            ...    ...        ...   
7782          2005  TV-MA     99 min   
7783          2015  TV-14    111 min   
7784          2019  TV-MA     44 min   
7785          2019  TV-PG   1 Season   
7786          2019  TV-MA     90 min   

                                              listed_in  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...   
1                          Dramas, International Movies   
2                   Horror Movies, International Movies   
3     Action & Adventure, Independent Movies, Sci-Fi...   
4                                                Dramas   
...                                                 ...   
7782                       Dramas, International Movies   
7783     Dramas, International Movies, Music & Musicals   
7784  Documentaries, International Movies, Music & M...   
7785                 International TV Shows, Reality TV   
7786                    Documentaries, Music & Musicals   

                                            description  \
0     In a future where the elite inhabit an island ...   
1     After a devastating earthquake hits Mexico Cit...   
2     When an army recruit is found dead, his fellow... 

In [12]:
cm = CountVectorizer().fit_transform(df['important_features'])

In [13]:
cs = cosine_similarity(cm)
print(cs)

[[1.         0.12337742 0.05900529 ... 0.22167555 0.10529233 0.24393469]
 [0.12337742 1.         0.04448841 ... 0.12535305 0.         0.02299002]
 [0.05900529 0.04448841 1.         ... 0.02398006 0.02278028 0.04397995]
 ...
 [0.22167555 0.12535305 0.02398006 ... 1.         0.15404885 0.32219304]
 [0.10529233 0.         0.02278028 ... 0.15404885 1.         0.14126448]
 [0.24393469 0.02299002 0.04397995 ... 0.32219304 0.14126448 1.        ]]


In [14]:
cs.shape

(7787, 7787)

In [15]:
Title = 'The Conjuring'

In [16]:
Show_id = df[df.title == Title]['show_id'].values[0]

In [17]:
scores = list(enumerate(cs[Show_id]))

In [18]:
sorted_scores = sorted(scores, key = lambda x:x[1], reverse = True)
sorted_scores = sorted_scores[1:]

In [19]:
print(sorted_scores)

[(5463, 0.3673154433462264), (6925, 0.363766418634276), (6277, 0.3603183178894028), (6566, 0.34720966422940736), (1018, 0.3362963545672746), (280, 0.31518754028368906), (6772, 0.3125270551058903), (6616, 0.30004959907448947), (3590, 0.29880715233359845), (2653, 0.29576024087563857), (7658, 0.29576024087563857), (4481, 0.29508444542532697), (6148, 0.29508444542532697), (3279, 0.29424494316824984), (6564, 0.2929990168526046), (5427, 0.29160592175990213), (6617, 0.2911569516371818), (6929, 0.28917761562712796), (6213, 0.28867513459481287), (492, 0.28792888138282696), (6830, 0.2870846258816073), (808, 0.28656336421531353), (5333, 0.28613169175965075), (6188, 0.2861316917596507), (6585, 0.2861316917596507), (573, 0.28571428571428575), (6898, 0.28507865803991933), (2992, 0.2849614140875866), (2235, 0.2836832573067901), (6912, 0.2836832573067901), (7700, 0.28365431446558775), (3955, 0.2827673179077792), (4285, 0.28237248320100705), (6861, 0.28237248320100705), (7434, 0.28124019129160777), (22

In [20]:
j=0
print('The 7 most recommended movies to',Title, 'are:\n')
for item in sorted_scores:
 movie_title = df[df.show_id == item[0]]['title'].values[0]
 print(j+1, movie_title)
 j = j+1
 if j>6:
    break

The 7 most recommended movies to The Conjuring are:

1 Secret of Success
2 The Theory of Everything
3 The Day Will Come
4 The Last O.G.
5 Bobby Jasoos
6 ABCD: Any Body Can Dance
7 The Polka King
